#!/bin/sh

set -e

# ensure that only system paths are searched for all the utilities
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin
export PATH

user_id="`id -u $PAM_USER`"
if [ "$PAM_TYPE" = "auth" ]; then
  if [ "`id -u`" -eq 0 ]; then
    systemctl start keepassxc-unlock@$user_id.service
  fi
elif [ "$PAM_TYPE" != "open_session" -a "$PAM_TYPE" != "close_session" ]; then
  echo unexpected PAM_TYPE $PAM_TYPE
  exit 1
fi
